# Generated by Django 5.0 on 2024-02-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytodolist',
            name='time_interval',
            field=models.CharField(max_length=50),
        ),
    ]
